# Generated by Django 4.2.16 on 2024-11-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vps_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('storage', models.IntegerField()),
                ('os', models.CharField()),
                ('type', models.CharField()),
                ('user', models.CharField()),
            ],
        ),
    ]
