# Generated by Django 4.2.16 on 2024-11-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps_details',
            name='status',
            field=models.CharField(default='Stopped'),
        ),
        migrations.AddField(
            model_name='vps_details',
            name='task_id',
            field=models.CharField(default='None'),
        ),
    ]
